version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/hello-jakarta
    ports:
      - "8080:8080"
    command: /opt/tomcat/bin/catalina.sh run
